### ISSUE TITLE
onvif dependency error

### ISSUE THREAD

**Issue by jcorreaes** [JurajNyiri/HomeAssistant-Tapo-Control#477]
### Description

Tapo Control is not working.

onvif dependency is always getting an error.

When restarting HA the same errors on notifications:

![Screenshot 2023-11-26 at 08 35 00](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/4310/25fac081-3475-42ca-83bc-30aa6ee35cd4)

When trying to set up a new camera entry on configuration:
![Screenshot 2023-11-26 at 08 27 28](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/4310/6eb5b4c1-2858-477f-a755-a6f54ffd13ae)

### Reproduction Steps

See screenshots in the description

### Expected behavior

Expected to work as it did previously.

### If applicable, add error logs.

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 08:32:02 (1 occurrences)
Last logged: 08:32:02

Setup failed for onvif: Unable to import component: cannot import name 'NotificationManager' from 'onvif.client' (/srv/homeassistant/lib/python3.11/site-packages/onvif/client.py)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/onvif/__init__.py", line 31, in <module>
    from .device import ONVIFDevice
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/onvif/device.py", line 43, in <module>
    from .event import EventManager
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/onvif/event.py", line 11, in <module>
    from onvif.client import (
ImportError: cannot import name 'NotificationManager' from 'onvif.client' (/srv/homeassistant/lib/python3.11/site-packages/onvif/client.py)

---

Logger: homeassistant.setup
Source: setup.py:159
First occurred: 08:32:02 (1 occurrences)
Last logged: 08:32:02

Unable to set up dependencies of tapo_control. Setup failed for dependencies: onvif

---

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 08:32:02 (1 occurrences)
Last logged: 08:32:02

Setup failed for custom integration tapo_control: (DependencyError(...), 'Could not setup dependencies: onvif')

### Device Firmware

1.0.6 Build 230609 Rel.72971n

### Integration Version

5.4.12

### Using stream component

No

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Core 2023.11.3

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
It works on 2023.11.3 without any issues. Make sure you can run homeassistant onvif integration without any issues in your environment. You are probably using unsupported env with outdated packages.
