### ISSUE TITLE
Incompatible with 1.0.0(b0)? - Solution: Use NEXT branch!

### ISSUE THREAD

**Issue by BoneheadFraggle** [JurajNyiri/HomeAssistant-Tapo-Control#43]
**Describe the bug**
I used 2.2.3 with HA 0.118.4 which worked great.

Now I just installed HA 1.0.0b0 and noticed that the `binary_sensor` was `unavailable`.
Upgraded to 2.3, no difference. Removed the previously configured cameras, tried to add again but got "Unknown error" when trying to add them.

Removed the integration, restarted, installed 2.3 again, restarted.
Tried to add again but got "Unknown error" when trying to add them.

![image](https://user-images.githubusercontent.com/2287810/101188570-30475280-3656-11eb-9351-0a210bcd4b4a.png)

**Expected behavior**
It worked fine before upgrading to 1.0.0b0, so I hoped it would work with 1.0.0b0 as well.

**Log**
If applicable, add error logs.
I do get this, so it is at least loaded correctly:
```
WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Camera (please complete the following information):**
 - Device Model: 2 x C200, but I can't add them

**Using stream component**
[no]

**Camera works through onvif component OR different cameras work in general**
[yes]

**Camera has all attributes filled out properly in developer tools**
It's not added at all.

**HASS Environment**
HassOS on NUC

**Additional context**
It worked fine before upgrading to 1.0.0b0, so I hoped it would work with 1.0.0b0 as well. My first guess would some kind of incompatibility with this version, but I can't be sure.

The cameras work fine in VLC and in the Tapo app.

**Comment by JurajNyiri** [comment]
Hey, check for the error in the log once you get unknown error. Then please paste it here.

**Comment by BoneheadFraggle** [comment]
`2020-12-05 11:45:47 ERROR (MainThread) [custom_components.tapo_control] __init__() got an unexpected keyword argument 'loop'`

**Comment by BoneheadFraggle** [comment]
It doesn't matter if I enter valid crendentials or juat bougus text, the error is immediate and the same.

**Comment by JurajNyiri** [comment]
Hey, this means they probably significantly changed internals so many integrations might be incompatible.
I will wait for a full release and once its released I will make it compatible ASAP if there is a need.

**Comment by JurajNyiri** [comment]
@BoneheadFraggle Good news! 

You can use https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/tree/next branch with the latest home assistant version 1.0.0b1.

I cannot release this yet until Home Assistant 1.0.0 is released. All the future version of this integration will be working only on Home Assistant 1.0.0 and above.

**Hello future visitors 👋**, if Home Asssistant 1.0.0 has been released recently, and you have not yet received an official update for the component, use [this](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/tree/next) version!

**Comment by BoneheadFraggle** [comment]
Just tested a little, but so far it works fine. 
Great work!
Thanks!
