### ISSUE TITLE
Setup failed after updating Home Assistant Core to 2023.5 beta

### ISSUE THREAD

**Issue by jjvelar** [JurajNyiri/HomeAssistant-Tapo-Control#323]
### Description

I am getting this error in Home Assistant Core log after updating to beta version 2023.05:

Setup failed for custom integration tapo_control: Unable to import component: cannot import name 'NotificationManager' from 'onvif.client' (/usr/local/lib/python3.10/site-packages/onvif/client.py)

### Reproduction Steps

Just updated and got the error.

### Expected behavior

Not getting the error.

### Device Firmware

Not related to any camera

### Using stream component

No

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Integration works without any issues both on 2023.6.0.dev20230430 and 2023.5.0b5. 
Make sure to use the latest version from releases or use 5.1.2 with the latest stable version of HA (as per today).

**Comment by jjvelar** [comment]
Sorry to ask but:
1) how do I know which is the Tapo integration version I have installed?, and
2) how do I force to install 5.1.6 release?
Thanks and best regards,

José

**Comment by jjvelar** [comment]
By the way, when tried to add the integration I get error message:

   Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by jjvelar** [comment]
> Integration works without any issues both on 2023.6.0.dev20230430 and 2023.5.0b5. Make sure to use the latest version from releases or use 5.1.2 with the latest stable version of HA - april release (as per today).

After updating to 5.1.6 it is working. Thanks!
