### ISSUE TITLE
Doesn't work for Home Assistant 2023.5.0

### ISSUE THREAD

**Issue by OldShaterhan** [JurajNyiri/HomeAssistant-Tapo-Control#328]
### Description

Integration is not working on HomeAssistant 2023.5.0.

### Reproduction Steps

Upgrade to 2023.5.0

### Expected behavior

Works as expected + https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/322 should work. 

### If applicable, add error logs.

Logger: homeassistant.setup
Source: setup.py:214
First occurred: 22:27:09 (1 occurrences)
Last logged: 22:27:09

Setup failed for custom integration tapo_control: Unable to import component: cannot import name 'NotificationManager' from 'onvif.client' (/usr/local/lib/python3.10/site-packages/onvif/client.py)

### Device Firmware

1.0.35 Build 230307 Rel.6847n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS on Raspberry Pi 4 B

### Search for similar issues

Yes

### Additional information

I updated, as I wanted to get motion sensor back (after update to 5.1.3+, as it didn't go back after downgrade to 5.1.2)

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/322

**Comment by JurajNyiri** [comment]
Upgrade to latest version.

**Comment by OldShaterhan** [comment]
Hi @JurajNyiri - just updated it seems that something went wrong initially and more it's okay, but still motion sensor is not appearing back for cam. How to restore it?

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/312

https://github.com/home-assistant/core/issues/91661

**Comment by OldShaterhan** [comment]
Okay, seems to be working. Not sure if that would help with original issue, but for me there are 2 motion sensor entities created now. @
![Screenshot_2023-05-03-23-28-28-893_io homeassistant companion android](https://user-images.githubusercontent.com/1622866/236053933-38c28936-77e7-4c9f-96c2-c0149f6a1799.jpg)

**Comment by jay1972** [comment]
Have the same problem. Ended up restoring my system

**Comment by OldShaterhan** [comment]
@jay1972 update to 2023.5.0, then upgrading Tapo to 1.3.7 (for 2023.4.x only 1.3.6 was available) seems to fix issue for me (except duplicated sensor)

**Comment by jay1972** [comment]
Cheers going to remove tapo before updating the HA Core then reinstall tapo

**Comment by jay1972** [comment]
That should prevent the duplicates

**Comment by JurajNyiri** [comment]
You can upgrade and if you see duplicates -- just remove the unavailable one and change the entity_id to the preferred ID to keep all automations working.
